library(ROCR)
library(RMySQL)

sqlStringRocData <- sqlImport("./roc_data.sql")
mydb             <- dbConnect(dbDriver("MySQL"),user="bbos",password="bbos",host="localhost",dbname="gameday")
rs.roc           <- dbSendQuery(mydb,sqlStringRocData)
df.roc           <- fetch(rs.roc,-1)
dbDisconnect(mydb)

pred.naive <- prediction(df.roc$naive,df.roc$c)
perf.naive <- performance(pred.naive,measure="tpr",x.measure="fpr")
auc.naive <- performance(pred.naive,measure="auc")
auc.naive <- unlist(slot(auc.naive,"y.values"))

pred.roeg <- prediction(df.roc$roeg,df.roc$c)
perf.roeg <- performance(pred.roeg,measure="tpr",x.measure="fpr")
auc.roeg <- performance(pred.roeg,measure="auc")
auc.roeg <- unlist(slot(auc.roeg,"y.values"))

pred.gen <- prediction(df.roc$nn_gen,df.roc$c)
perf.gen <- performance(pred.gen,measure="tpr",x.measure="fpr")
auc.gen <- performance(pred.gen,measure="auc")
auc.gen <- unlist(slot(auc.gen,"y.values"))

pred.pgen <- prediction(df.roc$nn_pdata,df.roc$c)
perf.pgen <- performance(pred.pgen,measure="tpr",x.measure="fpr")
auc.pgen <- performance(pred.pgen,measure="auc")
auc.pgen <- unlist(slot(auc.pgen,"y.values"))

jpeg('roc1.jpg')
plot(perf.naive,col="grey")
# plot(perf.roeg,add=TRUE,col="green")
plot(perf.gen,add=TRUE,col="red")
# plot(perf.pgen,add=TRUE,col="blue")
auc.s.naive <- paste("Naive model =",round(auc.naive,3))
# auc.s.roeg <- paste("Rates by bucket =",round(auc.roeg,3))
auc.s.gen <- paste("Basic NN =",round(auc.gen,3))
# auc.s.pgen <- paste("Pitch data NN AUC =",round(auc.pgen,3))
legend(0.5,0.4,c(auc.s.naive,auc.s.gen,"\n"))
# legend(0.5,0.4,c(auc.s.naive,auc.s.roeg,auc.s.gen,"\n"))
# legend(0.5,0.4,c(auc.s.naive,auc.s.roeg,auc.s.gen,auc.s.pgen,"\n"))
dev.off()

jpeg('roc2.jpg')
plot(perf.naive,col="grey")
# plot(perf.roeg,add=TRUE,col="green")
plot(perf.gen,add=TRUE,col="red")
plot(perf.pgen,add=TRUE,col="blue")
auc.s.naive <- paste("Naive model =",round(auc.naive,3))
# auc.s.roeg <- paste("Rates by bucket =",round(auc.roeg,3))
auc.s.gen <- paste("Basic NN =",round(auc.gen,3))
auc.s.pgen <- paste("NN w/movement =",round(auc.pgen,3))
legend(0.5,0.4,c(auc.s.naive,auc.s.gen,auc.s.pgen,"\n"))
# legend(0.5,0.4,c(auc.s.naive,auc.s.roeg,auc.s.gen,auc.s.pgen,"\n"))
dev.off()
